/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanaspruebas;

import controladores.ControladorCitas;
import controladores.ControladorClientes;
import controladores.ControladorOficiales;
import controladores.ControladorPruebas;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelos.Cita;
import modelos.Cliente;
import modelos.Oficial;
import modelos.Prueba;
import ventanascitas.JDialogBuscarCitas;
import ventanasoficiales.JDialogBuscarOficiales;

/**
 *
 * @author mata6
 */
public class AgregarPruebas extends javax.swing.JInternalFrame {
    private Prueba prueba;
    private ControladorPruebas cPrueba;
    private Cliente cliente;
    private ControladorClientes cCliente;
    private Oficial oficial;
    private ControladorOficiales cOficial;
    private Cita cita;
    private ControladorCitas cCita;
    private boolean oficialSelect;
    private boolean citaSelect;
    
    /**
     * Creates new form AgregarCitas
     */
    public AgregarPruebas() {
        initComponents();
        cPrueba = new ControladorPruebas();
        cCliente = new ControladorClientes();
        cOficial = new ControladorOficiales();
        cCita = new ControladorCitas();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaOficial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnOficial = new javax.swing.JButton();
        btnSeleccionarCitas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombreOficial = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesTxt = new javax.swing.JTextArea();
        BoxEstadoCliente = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BoxNota = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Hora:");

        txtCedulaOficial.setEditable(false);
        txtCedulaOficial.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cedula Oficial:");

        btnOficial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOficial.setText("Seleccionar Oficial");
        btnOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOficialActionPerformed(evt);
            }
        });

        btnSeleccionarCitas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeleccionarCitas.setText("Seleccionar Citas");
        btnSeleccionarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCitasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cedula Cliente:");

        txtCedulaCliente.setEditable(false);
        txtCedulaCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtCedulaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaClienteKeyTyped(evt);
            }
        });

        txtHora.setEditable(false);
        txtHora.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nombre del cliente:");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nombre del oficial:");

        txtNombreOficial.setEditable(false);
        txtNombreOficial.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtFecha)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(106, 106, 106)
                        .addComponent(txtHora))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOficial)
                            .addComponent(btnSeleccionarCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreOficial)
                            .addComponent(txtCedulaOficial))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionarCitas)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOficial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedulaOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Observaciones de la Prueba:");

        observacionesTxt.setEditable(false);
        observacionesTxt.setColumns(20);
        observacionesTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        observacionesTxt.setRows(5);
        observacionesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                observacionesTxtKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(observacionesTxt);

        BoxEstadoCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BoxEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije el estado del cliente", "Ausente", "Presente" }));
        BoxEstadoCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxEstadoClienteItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BoxEstadoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoxEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nota:");

        BoxNota.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BoxNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije una nota", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(BoxNota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BoxNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Prueba");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(287, 287, 287))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//cliente y cita activa
    private void btnSeleccionarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCitasActionPerformed
        JDialogBuscarCitas buscarCitas = new JDialogBuscarCitas(null,true);
        buscarCitas.setVisible(true);
        
        if (( cita=buscarCitas.getCita() )!=null) {
            this.txtFecha.setEditable(true);
            this.txtHora.setEditable(true);
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd"); 
            this.txtFecha.setText(f.format(cita.getFecha()));
            this.txtHora.setText(cita.getHora());
            this.txtHora.setEditable(true);
            this.txtHora.setEditable(true);
            
            cliente = cita.getCliente();
            this.txtCedulaCliente.setEditable(true);
            this.txtNombreCliente.setEditable(true);
            this.txtCedulaCliente.setText(String.valueOf(cliente.getCedula()));
            this.txtNombreCliente.setText(cliente.getNombre());
            this.txtCedulaCliente.setEditable(false);
            this.txtNombreCliente.setEditable(false);
            
            citaSelect = buscarCitas.isSeleccionado();
        }
     
    }//GEN-LAST:event_btnSeleccionarCitasActionPerformed

    private void btnOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOficialActionPerformed
        JDialogBuscarOficiales buscarOficiales = new JDialogBuscarOficiales(null,true);
        buscarOficiales.setVisible(true);
        
        if ((oficial=buscarOficiales.getOficial()) !=null){
            
            this.txtCedulaOficial.setEditable(true);
            this.txtNombreOficial.setEditable(true);
            this.txtCedulaOficial.setText(String.valueOf(oficial.getCedula()));
            this.txtNombreOficial.setText(oficial.getNombre());
            this.txtCedulaOficial.setEditable(false);
            this.txtNombreOficial.setEditable(false);
            
            oficialSelect = buscarOficiales.isSeleccionado();
        }
    }//GEN-LAST:event_btnOficialActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (this.citaSelect && this.oficialSelect && this.BoxEstadoCliente.getSelectedIndex()>0 && this.BoxNota.getSelectedIndex()>0) {
            prueba = new Prueba();
        
            prueba.setFecha(cita.getFecha());
            prueba.setHora(cita.getHora());
            prueba.setOficial(oficial);
            prueba.setCliente(cliente);

            if (this.BoxNota.getSelectedIndex()>0) {
                prueba.setNota(Integer.valueOf(String.valueOf(this.BoxNota.getSelectedItem())));
            }

            prueba.setObservaciones(this.observacionesTxt.getText());
            if (this.BoxNota.getSelectedIndex()>81) {
                prueba.setEstado(1);
            }else{
                prueba.setEstado(0);
            }

            if (this.cPrueba.ValidarFKCliente(prueba)) {
                
                if (this.cPrueba.ValidarFKOficial(prueba)) {
                    
                    if (this.cPrueba.ValidarFKFecha(prueba)) {
                        
                        if (this.cPrueba.ValidarFKHora(prueba)) {
                            
                            if (this.cPrueba.añadir(prueba)) {
                                
                                JOptionPane.showMessageDialog(this, "Prueba Agregada");
                              
                                cita.setEstado("desactivado");
                                cCita.actualizar(cita);
                                this.limpiar();
                                
                            }else{JOptionPane.showMessageDialog(this, "surgio un problema al añadir");}
    
                        }else{JOptionPane.showMessageDialog(this, "No se encuentra una cita para esa hora y que este acitva");}
                        
                    }else{JOptionPane.showMessageDialog(this, "No se encuentra una cita para esa fecha y que este activa");}
                    
                }else{ JOptionPane.showMessageDialog(this, "No se encuentra ese oficial");}
                
            }else{ JOptionPane.showMessageDialog(this, "No se encuentra ese cliente");}
            
        }else{ JOptionPane.showMessageDialog(this, "Debe seleccionar una cita,un oficial,asignar un estado al cliente y una nota para poder agregar");}
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void BoxEstadoClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxEstadoClienteItemStateChanged
        switch (this.BoxEstadoCliente.getSelectedIndex()) {
            case 1:
                this.observacionesTxt.setEditable(true);
                this.observacionesTxt.setText("El cliente no se presentó a la cita");
                this.observacionesTxt.setEditable(false);
                this.BoxNota.setSelectedIndex(1);
                this.BoxNota.setEnabled(false);
                break;
            case 2:
                this.observacionesTxt.setEditable(true);
                this.observacionesTxt.setText("");
                this.BoxNota.setEnabled(true);
                this.BoxNota.setSelectedIndex(0);
                break;
            default:
                this.observacionesTxt.setEditable(true);
                this.observacionesTxt.setText("");
                this.observacionesTxt.setEditable(false);
                this.BoxNota.setSelectedIndex(0);
                this.BoxNota.setEnabled(false);
                break;    
        }
    }//GEN-LAST:event_BoxEstadoClienteItemStateChanged

    private void txtCedulaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaClienteKeyTyped

    private void observacionesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_observacionesTxtKeyTyped
        
        
        if((this.observacionesTxt.getText().length()==60)){
             evt.consume();
        }
    }//GEN-LAST:event_observacionesTxtKeyTyped

    public void limpiar(){
        this.txtCedulaCliente.setText("");
        this.txtCedulaOficial.setText("");
        this.txtNombreCliente.setText("");
        this.txtNombreOficial.setText("");
        this.txtFecha.setText("");
        this.txtHora.setText("");
        this.BoxEstadoCliente.setSelectedIndex(0);
        
        cliente = null;
        oficial = null;
        cita = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxEstadoCliente;
    private javax.swing.JComboBox<String> BoxNota;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnOficial;
    private javax.swing.JButton btnSeleccionarCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea observacionesTxt;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaOficial;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreOficial;
    // End of variables declaration//GEN-END:variables
}
